In [14]:
import torch


In [15]:
torch.zeros([3,4])
torch.ones([3,4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                 [9, 10, 11, 12]])

x**2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [17]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])
mask = b>3
b[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
        18., 19., 20.])

In [18]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())
mask= x>limit

larger_than_limit_sum = torch.sum(x[mask])

print(larger_than_limit_sum)

tensor(39)


In [19]:
torch.cuda.is_available()

False

In [20]:
x = torch.rand([2,3])
x
torch.device('cuda:0')

device(type='cuda', index=0)

In [21]:
w = torch.tensor( [[1.,2.],[4.,5.]], requires_grad=True)

function = 10 * torch.log( ( w + 1. ) ).sum()

function.backward()

print(w-w.grad)

tensor([[-4.0000, -1.3333],
        [ 2.0000,  3.3333]], grad_fn=<SubBackward0>)


In [22]:
print ("a")

a
